# 配列 ['yaml1', 'yaml2', 'yaml3']
# - yaml1
# - yaml2
# - yaml3

# [0 => ['test1', 'test2', 'test3']]
# -
#   - test1
#   - test2
#   - test3

#ハッシュ(phpでは結局配列なのね)
#連想配列になるので便利
# yaml4: test4
# yaml5: test5
# yaml6: test6

#多次元
# yaml7:
#   yaml-a: test-a
#   yaml-b: test-b
#   yaml-c: test-c
# yaml8:
#   yaml-d: test-d
#   yaml-e: test-e
#   yaml-f: test-f

family:
  本人: 0
  父: 1
  母: 2
  兄: 3
  姉: 4

sex:
  男: 0
  女: 1
  その他: 2

trigger:
  ------: -1
  雑誌: 0
  テレビCM: 1
  ネット広告: 2
  検索: 3
  その他: 4